In [1]:
# Notebook Initialization
import numpy as np
import pandas as pd

# Loading Dataset
df = pd.read_csv("C:/Users/marco/Documents/Machine_Learning/Dataset/Indicadores_municipales_sabana_DA.csv", encoding='latin-1')
df

,ent,nom_ent,mun,clave_mun,nom_mun,pobtot_ajustada,pobreza,pobreza_e,pobreza_m,vul_car,...,pobreza_alim_10,pobreza_cap_90,pobreza_cap_00,pobreza_cap_10,pobreza_patrim_90,pobreza_patrim_00,pobreza_patrim_10,gini_90,gini_00,gini_10
0,1,Aguascalientes,1,1001,Aguascalientes,794304,30.531104,2.264478,28.266627,27.983320,...,11.805700,20.4,12.7,18.474600,43.4,33.7,41.900398,0.473,0.425,0.422628
1,1,Aguascalientes,2,1002,Asientos,48592,67.111172,8.040704,59.070468,22.439389,...,21.993299,39.9,29.0,30.980801,64.2,48.9,59.175800,0.379,0.533,0.343879
2,1,Aguascalientes,3,1003,Calvillo,53104,61.360527,7.241238,54.119289,29.428583,...,19.266800,39.5,33.1,28.259199,63.9,57.9,56.504902,0.414,0.465,0.386781
3,1,Aguascalientes,4,1004,Cosío,14101,52.800458,4.769001,48.031458,27.128568,...,14.303200,35.2,21.0,22.386101,59.7,40.1,51.164501,0.392,0.541,0.344984
4,1,Aguascalientes,5,1005,Jesús María,101379,45.338512,6.084037,39.254475,26.262912,...,15.085100,36.6,22.6,22.139999,60.6,42.2,45.703899,0.391,0.469,0.458083
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2451,32,Zacatecas,54,32054,Villa Hidalgo,21016,74.848837,12.301183,62.547654,19.229856,...,30.055300,51.8,54.8,41.368999,73.5,70.9,70.859596,0.403,0.589,0.342037
2452,32,Zacatecas,55,32055,Villanueva,27385,65.450191,10.203506,55.246687,23.623556,...,13.138800,34.2,25.9,20.563601,57.8,44.1,46.659199,0.422,0.463,0.362527
2453,32,Zacatecas,56,32056,Zacatecas,117528,29.541959,3.535624,26.006335,16.644262,...,7.164800,15.7,20.7,12.115300,36.6,41.8,32.302700,0.528,0.498,0.436339
2454,32,Zacatecas,57,32057,Trancoso,20456,78.374962,14.607016,63.767946,13.750759,...,21.285900,36.2,36.4,30.037100,60.5,54.7,57.394501,0.380,0.483,0.365307
2455,32,Zacatecas,58,32058,Santa María de la Paz,2772,62.204207,10.102023,52.102184,27.489635,...,18.688299,37.6,44.8,26.998899,61.2,63.9,54.116299,0.431,0.500,0.385067

In [2]:
# Preparing Dataset
df = df[[col for col in df.columns if col != 'rankin_p'] + ['rankin_p']]

# Extracting Value to Predict
Merida =  df.iloc[2341]
Merida = Merida.to_frame().T

# Reorder Dataset
df = df.drop(2341)
df = pd.concat([df, Merida])
df

,ent,nom_ent,mun,clave_mun,nom_mun,pobtot_ajustada,pobreza,pobreza_e,pobreza_m,vul_car,...,pobreza_cap_90,pobreza_cap_00,pobreza_cap_10,pobreza_patrim_90,pobreza_patrim_00,pobreza_patrim_10,gini_90,gini_00,gini_10,rankin_p
0,1,Aguascalientes,1,1001,Aguascalientes,794304,30.531104,2.264478,28.266627,27.98332,...,20.4,12.7,18.4746,43.4,33.7,41.900398,0.473,0.425,0.422628,2351
1,1,Aguascalientes,2,1002,Asientos,48592,67.111172,8.040704,59.070468,22.439389,...,39.9,29.0,30.980801,64.2,48.9,59.1758,0.379,0.533,0.343879,1340
2,1,Aguascalientes,3,1003,Calvillo,53104,61.360527,7.241238,54.119289,29.428583,...,39.5,33.1,28.259199,63.9,57.9,56.504902,0.414,0.465,0.386781,1601
3,1,Aguascalientes,4,1004,Cosío,14101,52.800458,4.769001,48.031458,27.128568,...,35.2,21.0,22.386101,59.7,40.1,51.164501,0.392,0.541,0.344984,1930
4,1,Aguascalientes,5,1005,Jesús María,101379,45.338512,6.084037,39.254475,26.262912,...,36.6,22.6,22.139999,60.6,42.2,45.703899,0.391,0.469,0.458083,2108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2452,32,Zacatecas,55,32055,Villanueva,27385,65.450191,10.203506,55.246687,23.623556,...,34.2,25.9,20.563601,57.8,44.1,46.659199,0.422,0.463,0.362527,1416
2453,32,Zacatecas,56,32056,Zacatecas,117528,29.541959,3.535624,26.006335,16.644262,...,15.7,20.7,12.1153,36.6,41.8,32.3027,0.528,0.498,0.436339,2364
2454,32,Zacatecas,57,32057,Trancoso,20456,78.374962,14.607016,63.767946,13.750759,...,36.2,36.4,30.0371,60.5,54.7,57.394501,0.38,0.483,0.365307,837
2455,32,Zacatecas,58,32058,Santa María de la Paz,2772,62.204207,10.102023,52.102184,27.489635,...,37.6,44.8,26.998899,61.2,63.9,54.116299,0.431,0.5,0.385067,1570
2341,31,Yucatán,50,31050,Mérida,897331,29.402434,3.295798,26.106635,28.496245,...,19.6,22.7,13.0619,42.2,44.0,35.2365,0.482,0.541,0.415666,2367

In [3]:
# Preparing Dataset

from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder for 'gender', oral', and 'tartar'
df['nom_ent'] = LabelEncoder().fit_transform(df['nom_ent'])
df['nom_mun'] = LabelEncoder().fit_transform(df['nom_mun'])
df['gdo_rezsoc00'] = LabelEncoder().fit_transform(df['gdo_rezsoc00'])
df['gdo_rezsoc05'] = LabelEncoder().fit_transform(df['gdo_rezsoc05'])
df['gdo_rezsoc10'] = LabelEncoder().fit_transform(df['gdo_rezsoc10'])

# Delate 'ent' Feature
df = df.drop(columns=['ent'])
df

,nom_ent,mun,clave_mun,nom_mun,pobtot_ajustada,pobreza,pobreza_e,pobreza_m,vul_car,vul_ing,...,pobreza_cap_90,pobreza_cap_00,pobreza_cap_10,pobreza_patrim_90,pobreza_patrim_00,pobreza_patrim_10,gini_90,gini_00,gini_10,rankin_p
0,0,1,1001,35,794304,30.531104,2.264478,28.266627,27.98332,8.419106,...,20.4,12.7,18.4746,43.4,33.7,41.900398,0.473,0.425,0.422628,2351
1,0,2,1002,124,48592,67.111172,8.040704,59.070468,22.439389,5.557604,...,39.9,29.0,30.980801,64.2,48.9,59.1758,0.379,0.533,0.343879,1340
2,0,3,1003,235,53104,61.360527,7.241238,54.119289,29.428583,2.921336,...,39.5,33.1,28.259199,63.9,57.9,56.504902,0.414,0.465,0.386781,1601
3,0,4,1004,430,14101,52.800458,4.769001,48.031458,27.128568,7.709276,...,35.2,21.0,22.386101,59.7,40.1,51.164501,0.392,0.541,0.344984,1930
4,0,5,1005,755,101379,45.338512,6.084037,39.254475,26.262912,8.279864,...,36.6,22.6,22.139999,60.6,42.2,45.703899,0.391,0.469,0.458083,2108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2452,31,55,32055,2214,27385,65.450191,10.203506,55.246687,23.623556,5.007426,...,34.2,25.9,20.563601,57.8,44.1,46.659199,0.422,0.463,0.362527,1416
2453,31,56,32056,2266,117528,29.541959,3.535624,26.006335,16.644262,8.828019,...,15.7,20.7,12.1153,36.6,41.8,32.3027,0.528,0.498,0.436339,2364
2454,31,57,32057,2110,20456,78.374962,14.607016,63.767946,13.750759,4.440331,...,36.2,36.4,30.0371,60.5,54.7,57.394501,0.38,0.483,0.365307,837
2455,31,58,32058,1692,2772,62.204207,10.102023,52.102184,27.489635,2.308246,...,37.6,44.8,26.998899,61.2,63.9,54.116299,0.431,0.5,0.385067,1570
2341,30,50,31050,980,897331,29.402434,3.295798,26.106635,28.496245,9.282588,...,19.6,22.7,13.0619,42.2,44.0,35.2365,0.482,0.541,0.415666,2367

In [4]:
# Mask for NaN Values
mask = df.isna()

# Print NaN Values
NaN = df[mask.any(axis=1)]
print(NaN)

      nom_ent  mun clave_mun  nom_mun pobtot_ajustada    pobreza  pobreza_e  \
137         4   58      7058     1012            4867   95.76583   55.47674
442        11   77     12077      892           12312  72.296225  34.316054
443        11   78     12078      382           15041  95.943368   82.60423
444        11   79     12079      776           15561  93.262955   71.41128
445        11   80     12080      790            5990  81.501586  45.568682
446        11   81     12081      687           10443  80.837921  53.684387
655        13  125     14125     1311           19006  70.095212  14.931804
778        16  123     15123      857           18992  81.911982   44.66233
779        16  124     15124     1343           69761  83.614996  47.324938
780        16  125     15125     2095           12180  51.955093   7.500403
1044       19   47     20047     1641             154  64.155932   8.144817
1811       22    9     23009     2122           23591  47.909783  10.311235
1990       27   14     28014      601            4619   73.28426   1.735067
2290       29  211     30211     1556           31788  61.756483  13.026139
2291       29  212     30212     1737           13388  91.572705  53.864904
2455       31   58     32058     1692            2772  62.204207  10.102023

      pobreza_m    vul_car   vul_ing  ... pobreza_cap_90 pobreza_cap_00  \
137   40.289089   3.786568   0.27805  ...           53.7            NaN
442   37.980172  22.839262  0.993324  ...           57.0           61.6
443   13.339138   4.056632       0.0  ...           94.4           93.1
444   21.851675   6.448964  0.044625  ...           90.3           94.8
445   35.932904  15.476967  0.698857  ...           69.0           71.6
446   27.153534  18.495706  0.048373  ...           75.6           90.2
655   55.163407   24.29385  2.616093  ...            NaN            NaN
778   37.249652  15.362599   0.59868  ...           54.5           68.0
779   36.290058  15.864791  0.117325  ...           67.9           80.2
780   44.454691  29.827088  5.933517  ...           20.3           15.6
1044  56.011116  35.844067       0.0  ...           29.5           66.0
1811  37.598547  43.274426  1.719094  ...            NaN            NaN
1990  71.549195  12.845682  7.164831  ...           14.4            9.1
2290  48.730344  30.805382  2.388075  ...           32.6           37.9
2291  37.707803   7.908356  0.254281  ...           68.1           77.0
2455  52.102184  27.489635  2.308246  ...           37.6           44.8

     pobreza_cap_10 pobreza_patrim_90 pobreza_patrim_00 pobreza_patrim_10  \
137         76.5205              76.6               NaN         92.996597
442       42.157299              77.0              78.0         65.926804
443       89.254097              98.1              98.3           97.3983
444         82.6185              97.0              98.5           94.8601
445       51.800201              85.6              85.6         75.983101
446       72.446999              89.6              95.8           89.2798
655       25.859501               NaN               NaN         51.226002
778       54.227901              74.6              83.2         77.350197
779       66.082603              85.6              92.2         86.727699
780         10.2409              43.8              36.9           27.9837
1044      41.696602              54.6              79.8         70.651703
1811      32.581699               NaN               NaN         59.588501
1990          6.713              32.1              23.3         21.007799
2290      21.443701              55.4              60.3           47.3381
2291      55.977501              85.6              89.7         82.203102
2455      26.998899              61.2              63.9         54.116299

     gini_90 gini_00   gini_10 rankin_p
137    0.354     NaN  0.308944       21
442    0.418   0.501  0.452733     1132
443    0.378   0.307  0.330353       17
444    0.336   0.353  0.327719       77
445    0.411   0.459  0.404884      668
446    0.385   0.392  0.361947      702
655      NaN     NaN  0.417816     1221
778     0.45   0.492  0.422408      649
779    0.371     0.4  0.354207      564
780    0.366    0.43  0.390359     1957
1044   0.349   0.487  0.301659     1473
1811     NaN     NaN  0.391811     2061
1990   0.459   0.572  0.464719     1086
2290   0.444   0.467  0.376755     1591
2291   0.382   0.426  0.307436      147
2455   0.431     0.5  0.385067     1570

[16 rows x 138 columns]

In [5]:
# Set NaN Values to a Mean Value
df.fillna(df.mean(), inplace=True)

# Print Comparison
NaN = df[mask.any(axis=1)]
print(NaN)

      nom_ent  mun  clave_mun  nom_mun  pobtot_ajustada    pobreza  pobreza_e  \
137         4   58       7058     1012             4867  95.765830  55.476740
442        11   77      12077      892            12312  72.296225  34.316054
443        11   78      12078      382            15041  95.943368  82.604230
444        11   79      12079      776            15561  93.262955  71.411280
445        11   80      12080      790             5990  81.501586  45.568682
446        11   81      12081      687            10443  80.837921  53.684387
655        13  125      14125     1311            19006  70.095212  14.931804
778        16  123      15123      857            18992  81.911982  44.662330
779        16  124      15124     1343            69761  83.614996  47.324938
780        16  125      15125     2095            12180  51.955093   7.500403
1044       19   47      20047     1641              154  64.155932   8.144817
1811       22    9      23009     2122            23591  47.909783  10.311235
1990       27   14      28014      601             4619  73.284260   1.735067
2290       29  211      30211     1556            31788  61.756483  13.026139
2291       29  212      30212     1737            13388  91.572705  53.864904
2455       31   58      32058     1692             2772  62.204207  10.102023

      pobreza_m    vul_car   vul_ing  ...  pobreza_cap_90  pobreza_cap_00  \
137   40.289089   3.786568  0.278050  ...       53.700000       51.478679
442   37.980172  22.839262  0.993324  ...       57.000000       61.600000
443   13.339138   4.056632  0.000000  ...       94.400000       93.100000
444   21.851675   6.448964  0.044625  ...       90.300000       94.800000
445   35.932904  15.476967  0.698857  ...       69.000000       71.600000
446   27.153534  18.495706  0.048373  ...       75.600000       90.200000
655   55.163407  24.293850  2.616093  ...       45.960228       51.478679
778   37.249652  15.362599  0.598680  ...       54.500000       68.000000
779   36.290058  15.864791  0.117325  ...       67.900000       80.200000
780   44.454691  29.827088  5.933517  ...       20.300000       15.600000
1044  56.011116  35.844067  0.000000  ...       29.500000       66.000000
1811  37.598547  43.274426  1.719094  ...       45.960228       51.478679
1990  71.549195  12.845682  7.164831  ...       14.400000        9.100000
2290  48.730344  30.805382  2.388075  ...       32.600000       37.900000
2291  37.707803   7.908356  0.254281  ...       68.100000       77.000000
2455  52.102184  27.489635  2.308246  ...       37.600000       44.800000

      pobreza_cap_10  pobreza_patrim_90  pobreza_patrim_00  pobreza_patrim_10  \
137        76.520500          76.600000          68.334121          92.996597
442        42.157299          77.000000          78.000000          65.926804
443        89.254097          98.100000          98.300000          97.398300
444        82.618500          97.000000          98.500000          94.860100
445        51.800201          85.600000          85.600000          75.983101
446        72.446999          89.600000          95.800000          89.279800
655        25.859501          67.096129          68.334121          51.226002
778        54.227901          74.600000          83.200000          77.350197
779        66.082603          85.600000          92.200000          86.727699
780        10.240900          43.800000          36.900000          27.983700
1044       41.696602          54.600000          79.800000          70.651703
1811       32.581699          67.096129          68.334121          59.588501
1990        6.713000          32.100000          23.300000          21.007799
2290       21.443701          55.400000          60.300000          47.338100
2291       55.977501          85.600000          89.700000          82.203102
2455       26.998899          61.200000          63.900000          54.116299

       gini_90   gini_00   gini_10  rankin_p
137   0.354000  0.460919  0.308944        21
442   0.418000  0.501000  0.452733      1132
443   0.378000  0.307000  0.330353        17
444   0.336000  0.353000  0.327719        77
445   0.411000  0.459000  0.404884       668
446   0.385000  0.392000  0.361947       702
655   0.400882  0.460919  0.417816      1221
778   0.450000  0.492000  0.422408       649
779   0.371000  0.400000  0.354207       564
780   0.366000  0.430000  0.390359      1957
1044  0.349000  0.487000  0.301659      1473
1811  0.400882  0.460919  0.391811      2061
1990  0.459000  0.572000  0.464719      1086
2290  0.444000  0.467000  0.376755      1591
2291  0.382000  0.426000  0.307436       147
2455  0.431000  0.500000  0.385067      1570

[16 rows x 138 columns]

In [6]:
# Features
x = df.drop(columns=['rankin_p'])[:-1].values
x

array([[0.00000000e+00, 1.00000000e+00, 1.00100000e+03, ...,
        4.73000000e-01, 4.25000000e-01, 4.22628105e-01],
       [0.00000000e+00, 2.00000000e+00, 1.00200000e+03, ...,
        3.79000000e-01, 5.33000000e-01, 3.43879312e-01],
       [0.00000000e+00, 3.00000000e+00, 1.00300000e+03, ...,
        4.14000000e-01, 4.65000000e-01, 3.86780888e-01],
       ...,
       [3.10000000e+01, 5.60000000e+01, 3.20560000e+04, ...,
        5.28000000e-01, 4.98000000e-01, 4.36338514e-01],
       [3.10000000e+01, 5.70000000e+01, 3.20570000e+04, ...,
        3.80000000e-01, 4.83000000e-01, 3.65307093e-01],
       [3.10000000e+01, 5.80000000e+01, 3.20580000e+04, ...,
        4.31000000e-01, 5.00000000e-01, 3.85066509e-01]])

In [7]:
# Target Variables
y = df['rankin_p'][:-1].values
y

array([2351, 1340, 1601, ..., 2364,  837, 1570], dtype=int64)

In [8]:
# Preparing Features for Prediction
x_predict = df.iloc[-1, :-1].values
x_predict

array([ 3.00000000e+01,  5.00000000e+01,  3.10500000e+04,  9.80000000e+02,
        8.97331000e+05,  2.94024339e+01,  3.29579800e+00,  2.61066347e+01,
        2.84962446e+01,  9.28258821e+00,  3.28187347e+01,  1.62292290e+01,
        2.07848168e+01,  4.14416320e+01,  8.02590825e+00,  1.05973199e+01,
        1.79631368e+01,  5.78986782e+01,  1.44037091e+01,  3.86850223e+01,
        7.60906192e+00,  2.31800000e+03,  2.63837000e+05,  2.95740000e+04,
        2.34263000e+05,  2.55706000e+05,  8.32960000e+04,  2.94493000e+05,
        1.45630000e+05,  1.86509000e+05,  3.71869000e+05,  7.20190000e+04,
        9.50930000e+04,  1.61189000e+05,  5.19543000e+05,  1.29249000e+05,
        3.47133000e+05,  6.82780000e+04,  1.60000000e+01,  4.90000000e+01,
        2.23650145e+00,  3.77261043e+00,  2.04344392e+00,  1.73050249e+00,
        2.29231238e+00,  2.58924127e+00,  2.22892857e+00,  3.26581144e+00,
        3.18025613e+00,  2.98879862e+00,  1.98695457e+00,  3.58365321e+00,
        1.70306361e+00,  2.32131100e+00,  7.05055000e+05,  7.81146000e+05,
        8.30732000e+05,  4.51180983e+00,  3.80778408e+00,  3.23098993e+00,
        3.91403007e+00,  2.58807397e+00,  2.51128006e+00,  4.13428917e+01,
        3.45963707e+01,  2.95828304e+01,  3.48741608e+01,  2.94262505e+01,
        2.32321606e+01,  1.52632999e+00,  6.66799128e-01,  8.12279999e-01,
        8.97474956e+00,  1.05878601e+01,  4.42426014e+00,  5.66362000e+00,
        3.04552889e+00,  2.42534995e+00,  1.59324799e+01,  8.11628056e+00,
        4.45030022e+00,  1.60393000e+00,  5.44163704e+00,  6.63950026e-01,
        2.90573692e+01,  2.33826504e+01,  2.02843800e+01,  1.69897099e+01,
        1.19472704e+01,  7.83405018e+00, -1.79238701e+00, -1.52265704e+00,
       -1.50490606e+00,  4.00000000e+00,  4.00000000e+00,  4.00000000e+00,
        2.38700000e+03,  2.38400000e+03,  2.39700000e+03,  2.15000000e+01,
        1.69000000e+01,  1.33105202e+01,  3.50000000e+01,  2.00878201e+01,
        3.70000000e+00,  1.10000000e+00,  6.96129978e-01,  3.90000000e+00,
        2.30000000e+00,  8.45049977e-01,  1.18000000e+01,  5.10000000e+00,
        8.20339978e-01,  1.97000000e+01,  1.26000000e+01,  7.47844982e+00,
        2.12000000e+01,  5.30000000e+00,  3.37759995e+00,  3.00000000e+01,
        1.78000000e+01,  4.65597010e+00,  4.30000000e+00,  1.30000000e+00,
        7.16769993e-01,  1.29000000e+01,  1.59000000e+01,  7.57110024e+00,
        1.96000000e+01,  2.27000000e+01,  1.30619001e+01,  4.22000000e+01,
        4.40000000e+01,  3.52364998e+01,  4.82000000e-01,  5.41000000e-01,
        4.15666312e-01])

In [14]:
# Split Dataset
def train_test_split_custom(x, y, test_size=0.2, random_state=0):
    np.random.seed(random_state)
    indices = np.random.permutation(x.shape[0])  # Shuffle the indices
    test_size = int(test_size * x.shape[0])  # Dataset Size
    test_indices, train_indices = indices[:test_size], indices[test_size:]  # Split the indices into train and test
    X_train, X_test = x[train_indices], x[test_indices]  # Use the indices to split the data
    y_train, y_test = y[train_indices], y[test_indices]  # Use the indices to split the labels
    return X_train, X_test, y_train, y_test  # Return the train and test data and labels

X_train, X_test, y_train, y_test = train_test_split_custom(x, y, test_size=0.2, random_state=0)

# Standardize Features
def standardize_features(X_train, X_test):
    mean = np.mean(X_train, axis=0)
    std = np.std(X_train, axis=0)
    X_train = (X_train - mean) / std  # Standardize the training data
    X_test = (X_test - mean) / std  # Standardize the test data
    return X_train, X_test


X_train, X_test = standardize_features(X_train, X_test)

# Create a KNN Regression model
def knn_regression(X_train, y_train, X_test, n_neighbors=5):
    y_pred = np.empty(X_test.shape[0])  # Storage
    for i in range(X_test.shape[0]):  # Iteration
        distances = np.sqrt(np.sum((X_train - X_test[i]) ** 2, axis=1))
        nearest_neighbors = np.argsort(distances)[:n_neighbors]
        y_pred[i] = np.mean(y_train[nearest_neighbors])  # Predict using Mean of KNN
    return y_pred

y_pred = knn_regression(X_train, y_train, X_test, n_neighbors=5)

In [15]:
y_predict = knn_regression(x, y, x_predict, 5)
predicted_rank = np.mean(y_predict)

print("Predicted Merida Poverty Ranking", predicted_rank)

Predicted Merida Poverty Ranking 2253.2

In [11]:
MeridaRank = df.iloc[-1, -1]
print('Merida Poverty Ranking: ', MeridaRank)

Merida Poverty Ranking:  2367

In [12]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Split Dataset
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

# Standardize Features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Create a KNN Regressor model
knn_regressor = KNeighborsRegressor(n_neighbors=5)
knn_regressor.fit(X_train, y_train)
y_pred = knn_regressor.predict(X_test)

In [13]:
# Prediction
x_predict = x_predict.reshape(1, -1) 
x_predict = scaler.transform(x_predict)
predicted_ranking = knn_regressor.predict(x_predict)
print("Predicted Poverty Ranking for Mérida:", predicted_ranking)

Predicted Poverty Ranking for Mérida: [2368.4]